services:
  db:
    build:
      context: .
      dockerfile: docker/localDb/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    # volumes:
    #   - migrate-db:/var/lib/postgresql/data